### PR TITLE
Sisby folks' assortment of output fixes and improvements

### LINKED ISSUE #12: [Bug]: Stringified Int Values prevent tasks from being completed
### Bug Description

Sometimes quest output will include values like `"amount": "16"`, `"count": "1"`, or `"lvl": "1"`.

These frequently make rewards wrong, or tasks uncompleteable.

[here's](https://github.com/sisby-folk/tinkerers-quilt/blob/1.19/config/ftbquests/quests/chapters/world.snbt) an example input (and [example output](https://github.com/sisby-folk/tinkerers-quilt/blob/33f7386a9ebb303dc0a7668d2ed819b6afbd87fa/config/heracles/quests/exploration/61E3A3B353DCD588.json)) if needed. 

Seems like the problem is that ftb is just _storing_ this stuff as strings even when the output spec requires ints. Maybe just special casing it is best? I can't possibly know how much this happens though.

### LINKED ISSUE #13: [Bug]: Various bits of missing FTB quests parity
### Bug Description

Hi hello! Here's a summary of missing spots I've found relating to fully translating FTB quests into heracles quests. This issue form is clunky and tedious, so i'm using one issue instead of 3.

- [x] Replace instances of `ftbquests:book` with `heracles:quest_book`
- [x] Dimension quests should default to being from `minecraft:overworld` instead of from `null`
- [x] Selectable rewards aren't converted
- [x] Non-GatherItem quest icons aren't passed through - e.g. a book for advancement tasks, a spyglass for stat tasks, spawn eggs for kill tasks, the structure block for structure tasks, a sapling for biome tasks. Task icon passthrough might just be added to heracles though.
- [x] Once https://github.com/terrarium-earth/Heracles/pull/86 is in, task names and (item) icons will need conversion, here's an example:

image

### LINKED ISSUE #15: [Bug]: nested quest folders aren't accepted by heracles
### Bug Description

Quests with groups and categories output in this format:

image

however, quests won't load unless the groups (e.g. `exploration` are on the top level of the `quests` folder, like so:

image

Additionally, a whole bunch of empty folders are generated, which seem unused. (maybe a minor error using something like mkdirs()?)

image

### PR DESCRIPTION
**Pull request by sisby-folk**
Couldn't think of a better title - and it's gonna be a lot easier to just slap this in and then refine later.

Closes #15 
Closes #13 (all 5 points)
Closes #12

[Tinkerer's Quilt](https://modrinth.com/modpack/tinkerers-quilt) ([quests.zip](https://github.com/terrarium-earth/odysseus/files/12826543/quests.zip)) parses in full straight out of odysseus, including all its icons and choice rewards and such.

image

image

Changes not detailed in issues:
 - Improves the readme and gitignore for basic usage
 - Reformats the quest overview as above - h2 subtitle, hr, tasks, hr, desc, hr, rewards.
 - Allows task override titles and icons to be inferred to quests.
 - Swaps the section sign `§` for the escaped formatter (`&&`) that heracles uses in quest descriptions.

Obvious improvements to make that I can't make
 - Use an actual package for converting int to hex for choice rewards instead of random linked source from a website. The builtin javascript stuff is genuinely not accurate enough, so something as good as the linked source.
 - Check backwards compatibility for some of the new input data. "works on my quests" is hard when FTB keeps changing their damned format.

### CODE REVIEW

File: odysseus/convertFtbQuests.ts [hunk 1]
```diff
@@ -70,7 +74,7 @@ type QuestTask = QuestObject & ({
 
     item: Item;
 
-    count?: number;
+    count?: string;
```
Comment (MsRandom) [inline odysseus/convertFtbQuests.ts:77]: What's the original type here in the SNBT?

File: odysseus/convertFtbQuests.ts [hunk 2]
```diff
@@ -134,14 +138,16 @@ type QuestTask = QuestObject & ({
 
 type QuestReward = BasicQuestObject & (Advancement | {
     type: FtbId<'choice'>;
+    table_id: string;
```
Comment (MsRandom) [inline odysseus/convertFtbQuests.ts:141]: Should be Long.

File: odysseus/convertFtbQuests.ts [hunk 3]
```diff
@@ -379,20 +393,49 @@ export const convertFtbQuests = async (input: QuestInputFileSystem, output: Ques
...
-                        if (task.type === 'heracles:item') {
-                            return {
-                                title: `Gather ${task.item}`,
-                                icon: task.item.startsWith('#') ? undefined : task.item
-                            };
+                        let title = undefined;
+                        let icon = undefined;
+                        if (task.title) title = task.title;
+                        if (task.icon) icon = task.icon;
+                        switch (task.type) {
```
Comment (MsRandom) [inline odysseus/convertFtbQuests.ts:400]: I feel like this should be a map rather than a switch statement.

File: odysseus/convertFtbQuests.ts [hunk 4]
```diff
@@ -478,6 +513,8 @@ function convertTask(task: QuestTask, questFile: QuestFile): HeraclesQuestTask {
         case "checkmark": {
```
Comment (MsRandom) [inline odysseus/convertFtbQuests.ts:513]: Since the `title` and `icon` here are shared between many types, why not make them into a variable then spread them into the individual types? like `...sharedData` or something similar

File: odysseus/convertFtbQuests.ts [hunk 5]
```diff
@@ -494,23 +531,29 @@ function convertTask(task: QuestTask, questFile: QuestFile): HeraclesQuestTask {
...
                 }
 
                 return {
                     type: 'heracles:item',
-                    amount: task.count,
-                    item: task.item.id,
+                    title: task.title,
+                    icon: task.icon ? convertIcon(task.icon) : undefined,
+                    amount: task.count ? parseInt(task.count) : undefined,
+                    item: task.item.id == 'ftbquests:book' ? 'heracles:quest_book' : task.item.id,
```
Comment (MsRandom) [inline odysseus/convertFtbQuests.ts:547]: This check is used before, should probably have an item sanitation function.

**Review by MsRandom — CHANGES_REQUESTED** [review]

File: odysseus/convertFtbQuests.ts (hunk 2 above)
Comment (sisby-folk) [reply odysseus/convertFtbQuests.ts:141]: I would love to have the answer to that question:

image

image

image

in practice, I know I had to manually replace stringified counts, amounts, and lvls with a pure number in json, so i'm playing defence.

Comment (MsRandom) [reply odysseus/convertFtbQuests.ts:141]: Yep long, so use the defined `Long` type. (it's defined as string but just so it's clearer)

File: odysseus/convertFtbQuests.ts (hunk 3 above)
Comment (sisby-folk) [reply odysseus/convertFtbQuests.ts:400]: uhh, i can see how that might work, but record of what type to what type?

File: odysseus/convertFtbQuests.ts (hunk 2 above)
Comment (MsRandom) [reply odysseus/convertFtbQuests.ts:141]: (For clarification)
https://github.com/terrarium-earth/odysseus/blob/main/odysseus/convertFtbQuests.ts#L21

File: odysseus/convertFtbQuests.ts (hunk 3 above)
Comment (MsRandom) [reply odysseus/convertFtbQuests.ts:400]: Key would be `HeraclesQuestTask['type']`, the value would probably some type that has functions to convert the the title etc.

File: odysseus/convertFtbQuests.ts (hunk 1 above)
Comment (sisby-folk) [reply odysseus/convertFtbQuests.ts:77]: I would love to have the answer to that question:

image

image

image

in practice, I know I had to manually replace stringified counts, amounts, and lvls with a pure number in json, so i'm playing defence.

parseInt(count.tostring()) would be fine too.

File: odysseus/convertFtbQuests.ts (hunk 4 above)
Comment (sisby-folk) [reply odysseus/convertFtbQuests.ts:517]: done in 644b643

File: odysseus/convertFtbQuests.ts (hunk 2 above)
Comment (sisby-folk) [reply odysseus/convertFtbQuests.ts]: done in 644b643

File: odysseus/convertFtbQuests.ts (hunk 5 above)
Comment (sisby-folk) [reply odysseus/convertFtbQuests.ts:548]: the book conversion is used in 3 spots, if that's what you mean? they have different types for their items though

Comment (MsRandom) [reply odysseus/convertFtbQuests.ts:548]: That's fine, just something like `getItemId(id: ResourceLocation)`

File: odysseus/convertFtbQuests.ts (hunk 2 above)
Comment (MsRandom) [reply odysseus/convertFtbQuests.ts]: Oh sorry, my comment was meant for the other review message, where you sent a few images showing a long count

File: odysseus/HeraclesQuest.ts [hunk 6]
```diff
@@ -199,9 +209,7 @@ export type HeraclesQuestTask = {
     amount?: number;
 } | {
     type: 'heracles:location';
-    icon?: ResourceLocation;
-    title: Component;
-    description: Component;
+    description: string;
```
Comment (MsRandom) [inline odysseus/HeraclesQuest.ts:212]: Any reason this is converted to `string`?

Comment (sisby-folk) [reply odysseus/HeraclesQuest.ts:212]: uhh this is mirroring me messing with it on the heracles end. Because everything has a title and icon override, and they use strings, the buggy use of component/text got changed.

File: odysseus/convertFtbQuests.ts (hunk 3 above)
Comment (sisby-folk) [reply odysseus/convertFtbQuests.ts]: function'd in 4e093f9

File: odysseus/convertFtbQuests.ts (hunk 5 above)
Comment (sisby-folk) [reply odysseus/convertFtbQuests.ts]: added in 4e093f9

File: odysseus/convertFtbQuests.ts (hunk 1 above)
Comment (MsRandom) [reply odysseus/convertFtbQuests.ts:77]: should use the `Long` utility type

Comment (sisby-folk) [reply odysseus/convertFtbQuests.ts]: done in 0120036

**Review by MsRandom — APPROVED** [review]
